import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-primary-background flex justify-center items-center ">
        <button className="bg-negative rounded p-3 text-white hover:bg-positive text-primary-text">
          Submit
        </button>
      </main>
    </>
  );
}
